# Generated by Django 5.2.4 on 2026-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(default='TEMP000', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
